---
title: "About"
about:
  template: solana

---

Welcome to my website! I'm Paul Simmering, an AI Engineer from Germany.

### Work

I work as Technical Expert GenAI Platforms & Services at [LBBW](https://www.lbbw.de), a leading German bank. I'm a developer on the GenAI team, building an enterprise-grade LLM chat application connected to internal data via RAG. In addition, I serve as an internal consultant for GenAI initiatives.

Between 2018 and mid-2025, I worked as Senior Data Scientist at [Q Agentur für Forschung](https://teamq.de), a market research agency. I worked on many projects for small and large businesses in consumer goods, pharmaceuticals, insurance and other industries. A large part of my work was productizing one-off projects into scalable data pipelines powered by languages models. Through that work, I got to experience the evolution of language understanding from bag-of-words models, to transformer models, to large language models.

My educational background is in economics. I hold a B.Sc. in Economics from the University of Mannheim and a M.Sc. in Economics from Aalborg University. During my master's degree, I discovered my passion for data science and decided to pivot to a career in the field. That worked out to be one of the best decisions I've made.


::: {.cv-timeline}

::: {.cv-entry}
[2025]{.cv-years}
[Technical Expert GenAI Platforms & Services]{.cv-title}  
[LBBW, Stuttgart]{.cv-org}
:::

::: {.cv-entry}
[2018 – 2025]{.cv-years}
[Data Analyst → Data Scientist → Senior Data Scientist]{.cv-title}  
[Q | Agentur für Forschung, Mannheim & remote]{.cv-org}
:::

::: {.cv-entry}
[2016 – 2018]{.cv-years}
[M.Sc. Innovation, Knowledge and Economic Dynamics (Economics)]{.cv-title}  
[Aalborg University]{.cv-org}
:::

::: {.cv-entry}
[2012 – 2015]{.cv-years}
[B.Sc. Economics]{.cv-title}  
[University of Mannheim]{.cv-org}
:::

:::

A more complete CV is available on my [LinkedIn profile](https://www.linkedin.com/in/paulsimmering/) or as a PDF on request. You can see examples of my work in the [projects](/projects.html) section.

I occasionally give [talks](/talks.html) at conferences and write [papers](/publications.html) on topics related to my work.

### Blog

On my [blog](/blog.html), I write about applied machine learning with a mix of technical articles, strategic insights and personal reflections. It's my practice of [learning in public](https://www.swyx.io/learn-in-public).

I prefer blogging over social media because it allows for more depth, has better tools for code and interactivity, and lets authors stay in control of their content. It lacks the algorithmic discovery and engagement that social media platforms offer, but content can be found through search engines and surfaced by AI assistants searching the web.

### Technical interests

- **LLM Evals & Monitoring**: The biggest barrier to scaled AI adoption in business is reliablity and evaluation is the key to proving it. Multi-step reasoning, agentic systems and multi-modal flows have made evaluation much harder than it was with classic NLP, but it's more important than ever.
- **Document understanding and RAG (Retrieval Augmented Generation)**: A huge amount of knowledge is stored in semi-structured documents, such as contracts, reports, emails and more. They need to be converted to a format LLMs understand, such as Markdown or JSON. Finally, an LLM needs access to data that is relevant to a user's query, which is where RAG comes in.
- **Data-efficient model fine-tuning**: Going beyond prompting by fine-tuning a model with your own data is a powerful way to improve model performance and enable accuracy that isn't possible with prompting alone. Techniques like LoRA make it cost-efficient.
- **Data storytelling**: The best data is useless if it's not presented in a way that is understandable and actionable. I'm a big fan of Cole Nussbaumer Knaflic's [Storytelling with Data](https://www.storytellingwithdata.com) and curious about how AI can be used to bring aspects of it into automated report generation.
- **OSINT (Open-Source Intelligence)**: The internet offers a vast amount of data that could be used to enhance AI and business intelligence systems, such as news articles, social media posts, and more.

### Personal interests

- **Reading personal blogs**. Check out my [blogroll](/blogroll.qmd) for recommendations of lateral thinkers, deep dives and personal reflections. This is the healthier alternative to doomscrolling on social media.
- **Practical philosophy**. I keep a list of the [principles](/principles.qmd) that I find most useful for decision making and contentedness.
- **Economics**. I hold a B.Sc. in Economics from the University of Mannheim and a M.Sc. in Economics from Aalborg University. Professionally, I pivoted to data science but am still interested in public finance, regional development, pricing strategies and the intersection of sociology, psychology and economics.
- **Parks and gardens**, especially [Japanese gardens](/japanese_gardens.qmd). I'm lucky to live close to [Blühendes Barock](https://www.blueba.de/en/) in Ludwigsburg.
- **Board and card games**: [Euro-style board games](https://en.wikipedia.org/wiki/Eurogame), Magic: The Gathering, Poker, Backgammon and other games that involve luck in a single game but are skill-based in the long run. I also like games involving trading and auctions, such as [Power Grid](https://en.wikipedia.org/wiki/Power_Grid), [Figgie](https://www.figgie.com) and [Bohnanza](https://en.wikipedia.org/wiki/Bohnanza).
- **Video games**. Particular favorites are: Guild Wars, Baldurs Gate 3, Satisfactory, the Hitman series and the Dark Souls series. Playing as a trader in EVE Online as a teenager drew me to economics and programming.

### What I use

I'm a bit of a gearhead and enjoy reading "what I use" lists of others, so here's mine: [What I use](/uses.qmd).

### Contact

If you find the topics I mentioned above interesting, I would enjoy hearing from you. The best way to contact me is via email: [paul@simmering.dev](mailto:paul@simmering.dev).

### Colophon

This website is built with [Quarto](https://quarto.org) and uses the Solana theme with some customizations. Posts are written in Markdown and may contain executable code blocks, which are executed and rendered as static HTML. The font is [Inter](https://rsms.me/inter/) for text and [JetBrains Mono](https://www.jetbrains.com/lp/mono/) for code. The website hosted on [Netlify](https://www.netlify.com). The source is available on [Github](https://github.com/psimm/website).
