# Privacy Policy

## 1. Privacy at a glance - General information

The following notes give a simple overview of what happens to your personal data when you visit this website. Personal data refers to all data that can identify you personally. For detailed information on the subject of data protection, please refer to our privacy policy listed below this text.

### Data collection on this website

### Who is responsible for data collection on this website?

The data processing on this website is carried out by the website operator. You can find his contact details in the section "Notice of the responsible body" in this privacy policy.

### How do we collect your data?

We collect your data when you provide it to us. This could, for example, be data that you enter into a contact form.

Other data is automatically collected or collected with your consent when you visit the website through our IT systems. These are mainly technical data (e.g. internet browser, operating system or time of webpage view). The collection of these data occurs automatically as soon as you enter this website.

We use [Goat Counter](https://www.goatcounter.com) to analyze the traffic on this website. It does not track any personal information and does not use cookies. See their [privacy policy](https://www.goatcounter.com/help/privacy) for more information.

### What do we use your data for?

Some of the data is collected to ensure that the website is error-free. Other data may be used to analyze your user behavior.

### What rights do you have regarding your data?

You have the right to receive information about the origin, recipient and purpose of your stored personal data free of charge at any time. You also have the right to request the correction, blocking or deletion of this data. You can contact us at any time at the address given in the imprint for this and other questions on the subject of data protection. Furthermore, you have the right to appeal to the responsible supervisory authority.

## 2. Hosting

### External hosting

This website is externally hosted. The personal data collected on this website are stored on the servers of the host or hosts. This data mainly includes IP addresses, contact requests, meta and communication data, contract data, contact details, names, website accesses, and other data generated through a website.

The external hosting is carried out for the purpose of fulfilling contracts with our potential and existing customers (Art. 6 Para. 1 lit. b GDPR) and in the interest of a secure, fast, and efficient provision of our online offer by a professional provider (Art. 6 Para. 1 lit. f GDPR). If appropriate consent was requested, the processing is carried out exclusively on the basis of Art. 6 Para. 1 lit. a GDPR and § 25 Para. 1 TTDSG, insofar as the consent includes the storage of cookies or access to information on the user's terminal device (e.g., device fingerprinting) in the sense of the TTDSG. The consent can be revoked at any time.

Our host(s) will only process your data to the extent necessary to fulfil its performance obligations and will comply with our instructions regarding this data.

We use the following host(s):

Netlify
44 Montgomery Street, Suite 300, San Francisco, California 94104, USA

## 3. General information and mandatory information

### Data protection

The operators of this website take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy.

When you use this website, various personal data are collected. Personal data refers to data that can be used to identify you personally. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this is done.

We would like to point out that data transmission over the Internet (e.g. communication by e-mail) can have security gaps. A complete protection of data against access by third parties is not possible.

### Notice of the responsible body

The responsible body for data processing on this website is:

Paul Simmering \
Jägerhofallee 30 \
71638 Ludwigsburg

E-Mail: paul@simmering.dev

The responsible body is the natural or legal person who alone or jointly with others decides on the purposes and means of processing personal data (e.g. names, e-mail addresses, etc.).

### Duration of storage

Unless a more specific storage period has been specified within this privacy policy, your personal data will remain with us until the purpose for the data processing no longer applies. If you assert a legitimate request for deletion or revoke your consent to data processing, your data will be deleted unless we have other legally permissible reasons for storing your personal data (e.g. tax or commercial retention periods); in the latter case, the data will be deleted after these reasons no longer apply.

### General information about the legal basis for data processing on this website

If you have given consent to data processing, we process your personal data based on Art. 6 Para. 1 lit. a GDPR or Art. 9 Para. 2 lit. a GDPR, if special categories of data according to Art. 9 Para. 1 GDPR are processed. In the case of explicit consent to the transfer of personal data to third countries, data processing also takes place on the basis of Art. 49 Para. 1 lit. a GDPR. If you have consented to the storage of cookies or to access information on your terminal device (e.g., via device fingerprinting), data processing also takes place based on § 25 Para. 1 TTDSG. Consent can be revoked at any time. If your data are necessary for contract fulfillment or for performing pre-contractual measures, we process your data based on Art. 6 Para. 1 lit. b GDPR. Furthermore, we process your data if they are necessary to fulfill a legal obligation based on Art. 6 Para. 1 lit. c GDPR. Data processing may also take place based on our legitimate interest pursuant to Art. 6 Para. 1 lit. f GDPR. The relevant legal bases in individual cases are informed about in the following paragraphs of this data protection declaration.

### Recipients of personal data

As part of our activities, we cooperate with various external parties. Sometimes a transfer of personal data to these external parties is also necessary. We only transfer personal data to external parties if this is necessary for contract fulfillment, if we are legally obliged to do so (e.g., transfer of data to tax authorities), if we have a legitimate interest in the transfer pursuant to Art. 6 Para. 1 lit. f GDPR or if another legal basis allows data transfer. When using contract processors, we only pass on customers' personal data based on a valid contract for order processing. In the case of joint processing, a contract for joint processing is concluded.

### Revocation of your consent to data processing

Many data processing operations are only possible with your explicit consent. You can revoke your consent at any time. The legality of the data processing up to the point of revocation remained unaffected by the revocation.

### Right to object to data collection in special cases and against direct advertising (Art. 21 GDPR)

IF THE DATA PROCESSING IS BASED ON ART. 6 ABS. 1 LIT. E OR F GDPR, YOU HAVE THE RIGHT AT ANY TIME TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA FOR REASONS ARISING FROM YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. PLEASE REFER TO THIS DATA PROTECTION DECLARATION FOR THE RESPECTIVE LEGAL BASIS ON WHICH PROCESSING IS BASED. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA, UNLESS WE CAN PROVE COMPELLING REASONS WORTHY OF PROTECTION FOR THE PROCESSING, WHICH OUTWEIGH YOUR INTERESTS, RIGHTS, AND FREEDOMS, OR THE PROCESSING SERVES TO ASSERT, EXERCISE, OR DEFEND LEGAL CLAIMS (OBJECTION ACCORDING TO ART. 21 ABS. 1 DSGVO).

IF YOUR PERSONAL DATA ARE PROCESSED FOR DIRECT ADVERTISING, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR THE PURPOSE OF SUCH ADVERTISING; THIS ALSO APPLIES TO PROFILING INSOFAR AS IT IS RELATED TO SUCH DIRECT ADVERTISING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE USED FOR THE PURPOSE OF DIRECT ADVERTISING (OBJECTION ACCORDING TO ART. 21 ABS. 2 DSGVO).

### Right to complain to the competent supervisory authority

In the event of violations of GDPR, the data subject has a right to complain to a supervisory authority, especially in the member state of their habitual residence, their place of work, or the place of the suspected violation. The right to complain exists without prejudice to other administrative or judicial remedies.

### Right to data portability

You have the right to have the data that we process automatically on the basis of your consent or in fulfillment of a contract handed over to you or to a third party in a common, machine-readable format. If you request the direct transfer of data to another person responsible, this will only be done if it is technically feasible.

### Information, correction, and deletion

Under the applicable legal provisions, you have the right at any time to free information about your stored personal data, their origin and recipients, and the purpose of the data processing and, if necessary, a right to correct or delete this data. For this as well as for further questions on the subject of personal data, you can contact us at any time.

### Right to restrict processing

You have the right to request the restriction of the processing of your personal data. You can contact us at any time for this. The right to restrict processing exists in certain cases.

- If you dispute the accuracy of your personal data stored with us, we generally need time to verify this. For the duration of the examination, you have the right to request the restriction of the processing of your personal data.
- If the processing of your personal data was/is unlawful, you can request the restriction of data processing instead of deletion.
- If we no longer need your personal data, but you need them to exercise, defend or assert legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion.
- If you have filed an objection according to Art. 21 para. 1 GDPR, a balance must be made between your and our interests. As long as it is unclear whose interests prevail, you have the right to request the restriction of the processing of your personal data.
- If you have restricted the processing of your personal data, these data may - apart from their storage - only be processed with your consent or to assert, exercise or defend legal claims or to protect the rights of another natural or legal person or for reasons of significant public interest of the European Union or a Member State.

Source: https://www.e-recht24.de
